; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Mon May 22 2017 13:17:01 GMT-0400 (Eastern Daylight Time)

; LAST UPDATE: 11/24/2017 3:29 PM -- EL




; Lift Z relatively to current position
G91
G1 Z5 F6000

; Back to absolute positioning
G90

; Go to middle of bed probe point and home the Z axis
G1 X238 Y180 F6000
G30

; Uncomment the following lines to lift Z after probing
; G91
; G1 Z5 F100
; G90

